Савичев Игорь
urfu-2016/qa-task-04 pull request #11
Opened 2017-05-02 20:04 UTC by Savichev-Igor

Завтра допилю тестов, глаза слипаются :<

2017-05-05 09:13 UTC, Dotokoto commented on tests/showTweets-test.js
> +    // TODO: Завтра, обещаю
> Завтра
>  Savichev-Igor commented 3 days ago 
Где тесты? >:(

2017-05-05 09:27 UTC, dotokoto requested changes
Жду еще тестов

2017-05-05 09:27 UTC, Dotokoto commented on formatDate.js
> +    months: months
Опять экспортишь константы ради тестов?

2017-05-05 09:27 UTC, Dotokoto commented on showTweets.js
> +                    item.created_at = formatDate(item.created_at);
Нехорошо в оригинальном объекте подменять поле

2017-05-05 20:57 UTC, Savichev-Igor commented
Тесты завезли, разгружайте =)

2017-05-10 06:26 UTC, Dotokoto commented on tests/showTweets-test.js
> +        console.log.restore();
Можно всё в один afterEach записать

2017-05-10 07:49 UTC, Dotokoto commented
Игорь, ты слишком быстро правишь, я еще досмотреть не успела ))

2017-05-10 07:50 UTC, Savichev-Igor commented
Я просто хочу тебе понравиться)

2017-05-10 07:55 UTC, Dotokoto commented
Азаза, не все бранчи покрыты
![build 91 - urfu-2016 qa-task-04 - travis ci 2017-05-10 12-51-55](https://cloud.githubusercontent.com/assets/8973726/25888413/8c6f83e2-357f-11e7-9bef-d21ed4d3f6cf.png)

2017-05-10 08:11 UTC, dotokoto requested changes
Теперь посмотрела )

2017-05-10 08:11 UTC, dotokoto commented on tests/showTweets-test.js
> +        assert(log.calledWith(`${parsedMockTweets[0].created_at}\n${parsedMockTweets[0].text}`));
Можно сделать так:
```
assert(log.firstCall.calledWith(...));
assert(log.secondCall.calledWith(...));
```

2017-05-10 08:11 UTC, Dotokoto commented on tests/formatDate-test.js
> +    let time = `${todayDate.getHours()}:${minutes}`;
Нуууу такое
Удобно конечно, но получается что ты перенес логику из кода в тесты. И если в ней ошибка, то тесты не сломаются, абидна будет

2017-05-17 13:15 UTC, Savichev-Igor commented on tests/formatDate-test.js
> +    let time = `${todayDate.getHours()}:${minutes}`;
Шаришь

2017-05-17 13:15 UTC, Savichev-Igor commented on tests/showTweets-test.js
> +        assert(log.calledWith(`${parsedMockTweets[0].created_at}\n${parsedMockTweets[0].text}`));
Круть)

2017-05-17 13:20 UTC, Savichev-Igor commented on tests/showTweets-test.js
> +        console.log.restore();
:3

2017-05-17 13:21 UTC, Savichev-Igor commented
@Dotokoto, done

2017-05-17 13:26 UTC, dotokoto approved these changes

2017-05-17 13:26 UTC, Dotokoto commented
Найс, принято 👍

2017-05-17 13:26 UTC, closed without merging