Исаков Федор
urfu-2016/qa-task-04 pull request #2
Opened 2017-04-30 20:53 UTC by FrodoTheTrue

2017-05-04 14:15 UTC, Zhigalov reviewed
Хорошо, но нужны доработки

2017-05-04 14:15 UTC, Zhigalov commented on .travis.yml
> +- npm run cover
В репозитории уже есть `.travis.yml`, для чего нужен ещё один?
https://github.com/urfu-2016/qa-task-04/blob/master/.travis.yml

2017-05-04 14:15 UTC, Zhigalov commented on formatDate.js
> +    throw new Error("formatDate take 1 argument");
Старайся в рамках одного проекта использовать кавычки одного типа, двойные или одинарные. Лучше одинарные.

2017-05-04 14:15 UTC, Zhigalov commented on formatDate.js
> +  } else {
Этот `else` не нужен

2017-05-04 14:15 UTC, Zhigalov commented on tests/formatDate-test.js
> +      });
Не понял чем содержимое этого теста отличается от предыдущего?

2017-05-04 14:15 UTC, Zhigalov commented on tests/formatDate-test.js
> +      });
Переходы через границы должны проверяться в объекте `Date`
Это не обязанность твоей библиотеки.

То есть как тестирование белого ящика - ❌ 
Как черного- ✅

2017-05-04 14:15 UTC, Zhigalov commented on tests/showTweets-test.js
> +        .get(`${twitterUrl.pathname}${twitterUrl.search}`)
search параметры можно преобразовать к JSON и передавать через `.query(...)`

2017-05-04 14:15 UTC, Zhigalov commented on tests/showTweets-test.js
> +const twitterUrl = new URL('https://api.twitter.com/1.1/search/tweets.json?q=%23urfu-testing-2016');
Зачем это выносить в переменную?
В твоём случае урл никогда не поменяется, ты можешь его заинлайнить.
Из-за этого твой тест станет более читаемый.
Надо стремиться к тому чтобы глядя на один тест вырванный из контекста было понятно что происходит

2017-05-04 14:15 UTC, Zhigalov commented on tests/showTweets-test.js
> +  });
В качестве крайнего случая в этом наборе тестов можно проверить что ничего не выведется на консоль если список твитов пустой

2017-05-07 15:57 UTC, FrodoTheTrue commented on tests/formatDate-test.js
> +      });
тут предполагалось проверить крайний случай: когда мы откатываемся на 1 день, но при этом меняется год и formatDate должен корректно сказать "вчера в ..."

2017-05-07 16:48 UTC, FrodoTheTrue commented on tests/showTweets-test.js
> +        .get(`${twitterUrl.pathname}${twitterUrl.search}`)
`.get('/1.1/search/tweets.json?q=%23urfu-testing-2016')` так работает
а так нет: `.get('/1.1/search/tweets.json')
    .query({ q : '%23urfu-testing-2016' })`

2017-05-07 16:48 UTC, FrodoTheTrue commented on tests/showTweets-test.js
> +        .get(`${twitterUrl.pathname}${twitterUrl.search}`)
не знаю почему

2017-05-08 11:49 UTC, Zhigalov requested changes

2017-05-08 11:49 UTC, Zhigalov commented on tests/showTweets-test.js
> +  });
Это замечание актуально

2017-05-08 11:49 UTC, Zhigalov commented on tests/showTweets-test.js
> +    .get('/1.1/search/tweets.json?q=%23urfu-testing-2016')
Попробуй не экранировать символ `%23` (это вроде # или @), тогда заработает

2017-05-11 05:54 UTC, Zhigalov commented
Принято

2017-05-11 05:54 UTC, closed without merging