Махаев Семён
urfu-2016/qa-task-04 pull request #3
Opened 2017-04-30 21:34 UTC by SemyonMakhaev

2017-05-16 08:26 UTC, mokhov requested changes
Есть что поправить и улучшить

2017-05-16 08:26 UTC, mokhov commented on formatDate.js
> +    const today = new Date(currentMoment);
Можно просто `new Date()`, за 4 строчки время вряд ли поменяется ;)

2017-05-16 08:26 UTC, mokhov commented on formatDate.js
> +    yesterday.setDate(yesterday.getDate() - 1);
Если будет 1 января, то будет ошибка

2017-05-16 08:26 UTC, mokhov commented on formatDate.js
> +        return getHoursAndMinutes(dateFromString);
функция вызывается несколько раз, её результат стоит закэшировать

2017-05-16 08:26 UTC, mokhov commented on tests/formatDate-tests.js
> +        const clock = sinon.useFakeTimers(new Date(2017, 2, 25, 16).getTime());
Почему это не в beforeEach?

2017-05-16 14:02 UTC, SemyonMakhaev commented on tests/formatDate-tests.js
> +        const clock = sinon.useFakeTimers(new Date(2017, 2, 25, 16).getTime());
beforeEach выполнится перед каждым тест-кейсом, в том числе, перед тест-кейсами другого describe - с тестами для showTweets. Они ломаются

2017-05-23 21:38 UTC, mokhov commented on tests/formatDate-tests.js
> +        const clock = sinon.useFakeTimers(new Date(2017, 2, 25, 16).getTime());
describe можно вкладывать в describe и как раз объединять тесты по такому признаку

2017-05-23 21:39 UTC, mokhov approved these changes
Ок

2017-05-23 21:39 UTC, closed without merging